### ISSUE TITLE
Consider open sourcing the framework

### ISSUE THREAD

**Issue by ianbytchek** [DevMate/DevMateKit#14]
It's an absolutely amazing library in terms of integrating with the service, but what's the reason behind it not being open source? 

That's not the selling point, your platform is. There's an open api that we can use, so in theory can build our own interface for feedback, etc. Besides, I imagine certain features the library provides can also be overwritten / tweaked. 

Being able to see the code makes it much easier to understand what's going on behind the scenes and customise it to fit individual app needs.

**Comment by SoneeJohn** [comment]
@ianbytchek I think the main reason why it's not open sourced is because of the activation code that's in it. I think in theory making something like that open source wouldn't be such a good idea. Everyone will know how the underlying activation algorithms work and could maybe use that knowledge pirating apps IMO. For example [Paddle](https://github.com/PaddleHQ/Mac-Framework) is also closed source maybe because it also has code for activation.

**Comment by ianbytchek** [comment]
Ah, that's a really good point. I've been dealing with the MAS version only, which doesn't come with that. Guess separating activation into a separate framework and adding it as a sub-framework could work?

**Comment by dimaty** [comment]
As you can see our framework sends some info to server (e.g. users feedback, user issue reports, tracking info, activation requests). This connections have own protocols for communication between user machine and DevMate server. We can not open source this protocols because of the next main reasons:
* protect our servers -> protect our clients info
* protect end user data
* protect apps from piracy by hiding licensing and obfustation algorithms

**Comment by ianbytchek** [comment]
Soneé made the same point on activation / licensing. Agree, makes sense. This business could be separated into a standalone framework and included as a sub-framework, pretty much like DevMateIssuesReporter is now. Everything else – I just spent 10 minutes getting Charles Proxy and watching everything what's going on over the SSL connection with devmate.com servers. Of course it provides a level of protection, but not the one anyone should rely upon to protect anything.

Don't want to make a wrong impression, I've been enjoying DevMate a lot recently. Just making a suggestion how to make it better.

**Comment by vslavik** [comment]
Licensing/activation code is *already* in libkevlar, which I agree is OK to remain binary-only. As @ianbytchek says, "protect our servers" is bogus, and the benefits of being able to debug problems myself or, yes, tweak things that are suboptimal and not easily customizable with the API, would be enormous.

For example: switching the activation/buy buttons order (as you did in 1.7) and adding a sales "what you get by upgrading" page in front, is something I inquired about a few months back and was told I could replace the pages completely, which would be unrealistically difficult. But it would be a simple matter if I had access to the source code.

For what it's worth (which is admittedly not much), while I too am enjoying the ease of shipping with DevMate a *lot* and use it for a smaller app, I'm cautions about switching to DevMate for my primary product, which already has other licensing code in place, and the dependence on a binary-only framework is a big part of that caution.

**Comment by tonyarnold** [comment]
Please consider making DevMateKit open source. The framework hasn't seen an update in over a year, and the lack of niceties like proper nullability annotations would be quick to fix.
