### ISSUE TITLE
Unable to export dev-signed app in Xcode 8.1

### ISSUE THREAD

**Issue by einsteinx2** [DevMate/DevMateKit#26]
I get the following error:

Failed to create provisioning profile. 
The app ID "com.devmate.Problem-Reporter" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.

I can create builds and archive them, but it seems impossible to export them to actually distribute them. I didn't have this issue until upgrading to Xcode 8.1 (though it may have occurred in 8 as well, I went pretty much directly from 7.3 to 8.1).

Any ideas?

**Comment by sdevore** [comment]
I only see this issue with Xcode 8.1 not with Xcode 8

**Comment by storyer** [comment]
Hi, that's Volodymyr here. 

It rather looks like you need to update bundle IDs of every app that DevMate Kit includes in order to pass that check. We've built in similar bundle id changer script to the MAS version of the Kit, it should help you with that. So what's needed: 

1) Locate all the apps: Autoupdate.app, Problem Reporter Sandboxed.app, Problem Reporter.app
2) Update their bundle ids with your app name inside, so they'll look like:  "your.app.bundle.com.devmate.Problem-Reporter" 
3) Sign the framework with your developer certificate, so that's it. 

Let us know if it works for you.

**Comment by einsteinx2** [comment]
I ended up just removing DevMate since it wasn't working.
