### ISSUE TITLE
Trial reset not working

### ISSUE THREAD

**Issue by Dids** [DevMate/DevMateKit#8]
Not every application can use the debug menu, and in my case I had to search for the code that actually does the resetting and manually trigger it when debugging.

Now, this code used to work, but it doesn't anymore, so I'm stuck on a trial that has run out of time.

Here's the code:
```objc
typedef BOOL (*DMTrialResetFuncPtr)(DMTrialRef);
static DMTrialResetFuncPtr __DMTrialReset = NULL;

static dispatch_once_t onceToken;
dispatch_once(&onceToken, ^{
    DMTrialHasTrialHistory(NULL);
    NSBundle *bundle = [NSBundle bundleForClass:[DMActivationController class]];
    CFBundleRef cfBundle = CFBundleGetBundleWithIdentifier((__bridge CFStringRef)[bundle bundleIdentifier]);
    void *variablePtr = CFBundleGetDataPointerForName(cfBundle, CFSTR("dm_rtfp"));
    __DMTrialReset = variablePtr ? *(DMTrialResetFuncPtr *)variablePtr : NULL;
});

if (NULL != __DMTrialReset)
{
    DLog(@"Resetting trial");
    __DMTrialReset([DMActivationController currentTrialController].trialObject);
}
else
{
    DLog(@"Necessary API is absent");
}
```

**Comment by dimaty** [comment]
Thank you for the report.

1.
 
> Not every application can use the debug menu, and in my case I had to search for the code that actually does the resetting and manually trigger it when debugging.

We understand it and that's why **DevMate Debug** menu is created using inline functions (this code is completely opened for you).

2.
> Now, this code used to work, but it doesn't anymore, so I'm stuck on a trial that has run out of time.

Unfortunately I could not reproduce this case. So I need more details from you:
* Is variable *__DMTrialReset* NULL or not?
* What is the way you're setting up your trial (e.g. using **+[DevMateKit setupTimeTrial...]** methods, using **+[DMActivationController timeTrial...]** method or using **DMTrialRef** API)?

**Comment by dimaty** [comment]
__DMTrialReset doesn't work because of absence of trial object (**[DMActivationController currentTrialController].trialObject** is NULL). That's why you should reset trial only after setting it up. Here are few cases how to "reset" trial correctly:
1) Reset trial right after it invalidates:
```Objective-C
// Implement delegate method
- (BOOL)activationController:(DMActivationController *)controller shouldShowDialogForReason:(DMShowDialogReason)reason withAdditionalInfo:(NSDictionary *)additionalInfo proposedActivationMode:(inout DMActivationMode *)ioProposedMode completionHandlerSetter:(void (^)(DMCompletionHandler))handlerSetter
{
    BOOL shouldShow = YES;
#ifdef DEBUG
    if (DMShowReasonTrialExpired == reason)
    {
        DLog(@"Trial is expired. Let's reset it and start new one.");
        [self resetTrial]; // this method resets trial using __DMTrialReset var
        [DevMateKit setupTimeTrial:self withTimeInterval:kDMTrialWeek];
        shouldShow = NO;
    }
#endif
    return shouldShow;
}
```
2) Start trial from the beginning if needs:
```Objective-C
// Implement another delegate method
- (BOOL)trialControllerShouldContinueLastSavedTrial:(DMActivationController *)controller
{
    BOOL shouldContinue = YES;
#ifdef DEBUG
    shouldContinue = ![self shouldResetTrial]; // method that could use NSUserDefaults for finding out or other ways
#endif
    return shouldContinue;
}
```

Hope, it will help you.

**Comment by Dids** [comment]
Thanks, makes sense. The only reason I wasn't resetting it afterwards was because the trial controller was blocking the thread, but doing it in delegate methods makes sense.
