### ISSUE TITLE
SUUpdater - Swift

### ISSUE THREAD

**Issue by valeIT** [DevMate/DevMateKit#9]
I've imported the header for it in my bridging header:

```
#import <DevMateKit/DevMateKit.h>
#import <DevMateKit/SUUpdater.h>
```

But when I call it from code it doesn't recognise it (it works perfectly for DevMateKit, but not for SUUpdater). I tried importing SUUpdater from on top of the swift file as well `import SUUpdater` to no avail (DevMateKit works without the import in the swift file).

```
func doesAutomaticallyCheckForUpdates() -> Bool {
  if  SUUpdater.sharedUpdater.automaticallyChecksForUpdates == true {
    return true
  } else {
    return false
  }
}

func switchAutomaticUpdates(toState toState: Bool) {
  if toState == true {
    SUUpdater.sharedUpdater.automaticallyChecksForUpdates = true
    SUUpdater.sharedUpdater.automaticallyDownloadsUpdates = true
  } else {
    SUUpdater.sharedUpdater.automaticallyChecksForUpdates = false
    SUUpdater.sharedUpdater.automaticallyDownloadsUpdates = false
  }
}
```

PS. The updater works from the xib, just I can't call it programmatically.

**Comment by dimaty** [comment]
Yes, we know about this kind of problem with Swift. Because some developers use their own Sparkle framework and to avoid names collision, DevMateKit has its own naming for Sparkle classes that starts with **DM_** prefix. For Obj-C we have special header with these defines (see _\<DevMateKit/DevMateSparkle.h>_ file). That is why your code written in objective-c works fine. But Swift doesn't work with macros, so you should use **DM_SUUpdater** class name instead of **SUUpdater** to fix your problem. Hope this will help you.

**Comment by valeIT** [comment]
Ah perfect, missed that. 

Thanks!
